### ISSUE TITLE
figure out how to version QGIS server backend

### ISSUE THREAD

**Issue by gubuntu** [kartoza/docker-geosafe#107]
_From @gubuntu on May 25, 2017 1:34_

How do we maintain QGIS server backend integration current with GeoNode 
- bring in QGIS server backend through pip
- as a django contrib module?
- be keeping it in a kartoza branch and doing PRs upstream when GeoNode changes.

_Copied from original issue: kartoza/geonode#224_

**Comment by Gustry** [comment]
Is it not sorted out as QGIS Server is now in Geonode core?

**Comment by lucernae** [comment]
Yeah, I think we can close it.
