### ISSUE TITLE
upgrade django version

### ISSUE THREAD

**Issue by gubuntu** [kartoza/docker-geosafe#110]
_From @boney-bun on October 9, 2017 11:13_

# problem:
the current django version is 1.8.7.
we can't use the latest build-in decorator such as *mixins* to easily control class-based view (ex: `geonode.maps.qgis_server_view.py` or `geosafe.views.analysis.py`). 
these decorators help us to control the authentication without doing so many refactoring into the existing view functions.

# proposed solution:
upgrading current django to either 1.9 or even 1.11 seems to be feasible.

_Copied from original issue: kartoza/geonode#356_

**Comment by gubuntu** [comment]
_From @Gustry on October 9, 2017 11:46_

I guess we should stick to the upstream geonode version. They are still using 1.8.7. https://github.com/GeoNode/geonode/blob/master/setup.py#L55.

Which feature would you like to you available only in 1.11?

If you need to do it, this should be done against geonode upstream, not our fork. Let's keep our fork as small as possible.

**Comment by gubuntu** [comment]
_From @boney-bun on October 9, 2017 14:24_

jump from 1.8 to 1.11 probably is a bold action.
maybe switch to 1.9 would have a slight improvement to the framework @Gustry ? 
the proposal to using django 1.9 aims to using [Permission mixins for class-based views](https://docs.djangoproject.com/en/1.11/releases/1.9/) decorator in the geosafe. 

if we could successfully deploy the new version to our project, there is a chance we could ask the upstream to do it too :)

**Comment by gubuntu** [comment]
_From @lucernae on October 10, 2017 6:10_

I actually agree with @Gustry . Even if they want to upgrade to 1.9, we should do that in upstream first.
It would be troublesome to merge the changes later.

**Comment by gubuntu** [comment]
_From @ismailsunni on October 10, 2017 9:37_

Jumping here. +1 also to upgrade it in upstream. i.e. make another branch from upstream, upgrade, make a PR, then after merged we update it from upstream. Merging too much code is not easy :D

**Comment by gubuntu** [comment]
_From @Gustry on October 10, 2017 10:1_

Maybe discuss first on the geonode dev list if we really need that.

Note that Django 1.11 is an LTS, so better to update to that one.

**Comment by lucernae** [comment]
As an update, GeoNode will use Django 1.11, but the code will be heavily refactored. So I think we need to provide some supports.

**Comment by gubuntu** [comment]
In our master / staging / production / releases we should use whatever Django version GeoNode 2.8 uses. 

In our development branches (for deployment on testing) we should use the Django version that GeoNode master / 2.9 uses, i.e. the one destined for the next GeoNode release.

**Comment by gubuntu** [comment]
@lucernae I'm assuming this is OK to close
