### ISSUE TITLE
Analysis not working. Just keeps spinning...

### ISSUE THREAD

**Issue by saravanaganesh18** [kartoza/docker-geosafe#115]
Update (latest):

Coordinates were edited manually to proper lat - long. But still, analysis part it not working. It keeps on spinning.

![image](https://user-images.githubusercontent.com/37054331/37595216-fe2a3fee-2b9d-11e8-8f71-50105c05e08a.png)

Most probably, this must be the issue reported here - https://github.com/kartoza/geosafe/issues/175. How to fix this ?

------------------

Previous Question

1) I've uploaded a raster layer (**_Earthquake: Hazard_**) in Kartoza server and in our server respectively. 

2) In Kartoza server, no issues with the analysis.

3) But in our server, the analysis process just keeps running (just spinning). First i thought this might be the issue raised here https://github.com/kartoza/geosafe/issues/175

4) But then, i noticed a strange issue. In Kartoza Server, Both the hazard layer and exposure layer were in the correct geographical location. But in our server, the raster layer (**_Earthquake: Hazard_**) was shifted

![1](https://user-images.githubusercontent.com/37054331/37255357-580678c6-2571-11e8-9096-d5b4b50825b2.png)

5) I checked the extent & metadata details. This is the screenshot of the raster in Kartoza server

![2](https://user-images.githubusercontent.com/37054331/37255305-7c4f09d8-2570-11e8-8014-28b7d5bd8e8b.png)

6) And, this is the screenshot of the raster in our server. One could notice, the location is correct in the map_preview window. But, the coordinates were swapped in Metadata Detail's column

![3](https://user-images.githubusercontent.com/37054331/37255314-c81f4404-2570-11e8-964f-8f08b49d81e5.png)

Path to the raster in our server: http://159.65.248.35/layers/geonode:padang_eq_2009_wgs84

Path to the raster in Kartoza's server: http://geonode.kartoza.com/layers/geonode:padang_eq_2009_wgs84

Any advise or guidance would be greatly appreciated. Thanks

**Comment by lucernae** [comment]
@saravanaganesh18 After I inspect it closely, this is probably because of the bug in the image you are currently using. So, I'm trying to fix a stable build. However to investigate further edge cases. Can you confirm that the only analysis here is the one that you are trying to run?:

http://159.65.248.35/geosafe/analysis/

**Comment by saravanaganesh18** [comment]
@lucernae I've added two other layers (MMI and Buildings). But still the issue persists.

Also, metadata - i am still manually editing the tags

![image](https://user-images.githubusercontent.com/37054331/37973163-8791eb42-31f7-11e8-93f3-02103c34ea10.png)

**Comment by gubuntu** [comment]
@saravanaganesh18 we are doing further work on GeoNode now as part of a WB contract and we hope to have a clear naming convention and versioning procedure established presently.

**Comment by saravanaganesh18** [comment]
@gubuntu  Thanks for the update. In case, if anyone want to check the issue, this is the new address: http://104.131.165.7/geosafe/analysis/create

More than a month, i am stuck at this point (analysis). Is it a version issue ?. I couldn't update celery, etc.. to latest version. 

![image](https://user-images.githubusercontent.com/37054331/39739535-00549480-52af-11e8-952d-7aafb2c5cfdf.png)

**Comment by gubuntu** [comment]
This issue was moved to kartoza/geosafe#290
