### ISSUE TITLE
Update Assets JS in UI

### ISSUE THREAD

**Issue by lucernae** [kartoza/docker-geosafe#117]
We made PR here: https://github.com/GeoNode/geonode/pull/3682

We are trying to fix Filter issues (not working) on GeoNode branch 2.7.x (what we used as stable branch). This is related with incomplete JS function using a wrong variable. Probably just a typo. Fixing this and rebuild assets js for production fixed it.

Related JS Console error:

```
Error: event is not defined
$scope.multiple_choice_listener@http://testing.geonode.kartoza.com/static/geonode/js/search/search.js?v=2.9.dev20171204131827:424:11
fn@http://testing.geonode.kartoza.com/static/lib/js/assets.min.js?v=2.9.dev20171204131827 line 32 > Function:4:374
e@http://testing.geonode.kartoza.com/static/lib/js/assets.min.js?v=2.9.dev20171204131827:33:5380
$eval@http://testing.geonode.kartoza.com/static/lib/js/assets.min.js?v=2.9.dev20171204131827:31:7415
$apply@http://testing.geonode.kartoza.com/static/lib/js/assets.min.js?v=2.9.dev20171204131827:31:7640
compile/</<@http://testing.geonode.kartoza.com/static/lib/js/assets.min.js?v=2.9.dev20171204131827:33:5430
dispatch@http://testing.geonode.kartoza.com/static/lib/js/assets.min.js?v=2.9.dev20171204131827:3:14421
add/q.handle@http://testing.geonode.kartoza.com/static/lib/js/assets.min.js?v=2.9.dev20171204131827:3:11231
```

This is a stack trace from compiled minified file. So, to track this you had to debug GeoNode in UI development mode. Luckily, the bug is in the js lib, so it is easier to track.

**Comment by gubuntu** [comment]
The GeoNode PR above was merged so can we close this @lucernae?

**Comment by gubuntu** [comment]
@lucernae I'm assuming this is OK to close
