### ISSUE TITLE
Geosafe doesn't show up

### ISSUE THREAD

**Issue by boney-bun** [kartoza/docker-geosafe#119]
# Problem
Click on geosafe, it will return:
```
NotRegistered at /geosafe/analysis/create
'headless.tasks.inasafe_wrapper.filter_impact_function'
```

On debug mode shows that while these tasks are registered on celery:
```
- headless.tasks.inasafe_wrapper.filter_impact_function
- headless.tasks.inasafe_wrapper.read_keywords_iso_metadata
- headless.tasks.inasafe_wrapper.run_analysis
```
The three tasks above are not reloaded on inasafe headless and inasafe headless analysis.
The error may occur on the `inasafe headless` and `inasafe headless analysis`.
The error may also due to the use of `celery 4.1.0` so that we need to refactor some codes.

# Solution
Still need to understand inasafe, but probably we need to make sure the headless tasks can be imported on inasafe headless and inasafe headless analysis.

**Comment by gubuntu** [comment]
@boney-bun please give more context - which versions, which images, what domain? Are you asking for help setting up a dev environment or is this a bug?

And if you are working on it please self-assign and give it the right labels

**Comment by boney-bun** [comment]
@gubuntu sorry... i think this is invalid issue.
it was a wrong branch.
i'm going to close this issue.
