### ISSUE TITLE
Extend Rancher orchestration to support theming of GeoNode

### ISSUE THREAD

**Issue by gubuntu** [kartoza/docker-geosafe#120]
We need to develop the code and deployment components to make it easy for a designer to change themes. This includes possibly packaging the theme override as another Django app and deploying it either as docker services / volumes or just a Django app. We also need to explain it for a designer to be able to override it using Django template and make live changes by him / herself.

ref https://github.com/kartoza/geonode/issues/420

copied from #105:
>1. make it easy to deploy skin updates by identifying the files that need to be changed and including them in the orchestration
>1. start by deploying the InaSAFE skin that was done a couple of years ago by Maria (with updates if necessary) to geonode.inasafe.org

child of https://github.com/kartoza/geonode/issues/458

**Comment by lucernae** [comment]
Update on this:

1. Custom skin are packaged as Django App. example on http://github.com/kartoza/ingc_geonode_theme

2. Let us standardize that custom skin app, have prefix geonode_theme for GeoNode theme

3. Apps are loaded through pip install on git repo. Example url will be `git+https://github.com/kartoza/ingc_geonode_theme.git@tagname`

4. Which skin app to use is asked by Rancher question (available when doing update or deploy)

5. Skin app development can follow regular Django development (package requirements were listed in the app).

Thus I will put this issue on feedback so we can close it.

**Comment by gubuntu** [comment]
LGTM, thanks @lucernae
