### ISSUE TITLE
Add tagline

### ISSUE THREAD

**Issue by carina1000** [kartoza/docker-geosafe#139]

**Comment by carina1000** [comment]
# Problem

Geosafe needs a tagline

# Solution

Implement Tagline:

"Realistic Natural Hazard Impact Analysis - InaSAFE made easy"
![Screen Shot 2018-08-28 at 11.08.18 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a533a594304490012b9cfb6/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772b6456fb6b7191a379ee0c2b59415e46bc30254d58eeb9cb74fce36f34985619e8d93c5b74976b47faec8b4cb852bb748b4ed4b7bb8349c8fa2137a5dad11b61435c52dcbd4f3fb2984cc259f348e44951a3103461e474376e0a.png)

**Comment by boney-bun** [comment]
i thought this was an issue in geosafe repo.

the PR is in kartoza/geosafe#350
could you kindly review it @carina1000 ?

**Comment by carina1000** [comment]
Yes, you're right - reviewed!

**Comment by boney-bun** [comment]
i'm going to close this issue.
the PR has been approved.
