### ISSUE TITLE
Add flower for celery monitoring

### ISSUE THREAD

**Issue by lucernae** [kartoza/docker-geosafe#18]
Flower is a celery monitoring tools.
We can use it to monitor InaSAFE workers.

**Comment by lucernae** [comment]
I still considered flower as a `nice to have`. If we're able to use rancher we might not need this. We'll just use rancher to restart the worker. Also, I found out that task status can be queried easily programmatically and recently used this to restart/cancel the task. 
However, there is still some problem with InaSAFE worker randomly killed because InaSAFE headless uses QGIS Server in a headless way, and QGIS seems didn't properly handled/expect that it will be used in a multithreaded graphical way. When the graphics buffer thread died we don't have any mechanism to detect this within the code.
Relevant article for possible workaround:
https://groups.google.com/forum/#!topic/celery-users/fzFqCMID7sU

**Comment by gubuntu** [comment]
@lucernae pls update or close

**Comment by gubuntu** [comment]
will use Rancher tools instead
