### ISSUE TITLE
No SMTP support

### ISSUE THREAD

**Issue by timlinux** [kartoza/docker-geosafe#36]
Trying to invite a user fails - it seems we have not SMTP support. I have already made a postfix docker container so you should be able to just include it in your orchestration and then set geonode to use that docker container.

child of https://github.com/kartoza/geonode/issues/457

**Comment by timlinux** [comment]
http://geonode.kartoza.com/account/invite_user/

![licecap](https://user-images.githubusercontent.com/178003/26851729-02bc00d8-4b0c-11e7-8e6d-176ebcff4e84.gif)

**Comment by gubuntu** [comment]
yes this will fix https://github.com/kartoza/geonode/issues/253

**Comment by gubuntu** [comment]
should fix https://github.com/kartoza/geonode/issues/462

**Comment by lucernae** [comment]
Steps to test in testing server:

# Testing user invitation:

1. Sign out from GeoNode in default browser. Open GeoNode from incognito mode
2. Invite user by providing email address that is yet to be registered
3. Check that the email is received in Inbox or Spam folder.
4. Click register/activate from the link provided
5. Link will redirect to current default browser. Proceed with registration.
6. After registration the new account will be created.

Troubleshoot.
1. If you haven't logout yet before you accept the invitation link, it is possible that the link will be accepted but the account was not created (GeoNode doesn't handle this use case).
2. To troubleshoot this, login using admin account. Go to Admin page. Go to Invitations models. Select your invitations then delete/deactivate it.
3. Continue testing procedure. But log out first from default browser. Mail client will use your invitation link directly using default browser

# Testing email address verification:

1. Make sure you already have an account and logged in.
2. Go to profile page > set/change email address.
3. Input email address or click verify email address
4. Check that email is received. Click confirm
5. Should redirect to default browser and have the account confirmed

# Testing password reset:

1. Login with wrong password
2. Click forgot password
3. Input your email address
4. Check email received and click reset password
5. Should redirect to default browser. Proceed to change the password
6. Log in with the new password.

CC @gubuntu @NyakudyaA

**Comment by lucernae** [comment]
I forgot to add. Maybe test while using Portuguese locale and see if the email is also in Portuguese? I don't think it was implemented by GeoNode, tho

**Comment by NyakudyaA** [comment]
@lucernae the email contains some Portuguese.
![pass](https://user-images.githubusercontent.com/2510900/47779854-cc2d6400-dd02-11e8-93d4-e249f9f08683.png)

I have tested this and I am happy about this behavior
