### ISSUE TITLE
Session time insecurity

### ISSUE THREAD

**Issue by gubuntu** [kartoza/docker-geosafe#40]
_From @gubuntu on June 13, 2017 11:59_

_From @MariaSolovyeva on March 24, 2017 12:36_

It seems that the site does not restrict the user’s session time. If a user does not sign out, the browser will always remember the user’s credentials.

_Copied from original issue: kartoza/geosafe#79_

_Copied from original issue: kartoza/geonode#268_

**Comment by gubuntu** [comment]
_From @boney-bun on June 12, 2017 15:18_

yes, this issue is still valid.
apparently, the session time is managed in the geonode.
so, we should move this issue to geonode instead of geosafe.
what do you think @gubuntu @lucernae ?

**Comment by gubuntu** [comment]
_From @lucernae on June 15, 2017 11:7_

This is a django settings, so we can set it independently.

https://docs.djangoproject.com/en/1.8/topics/http/sessions/#browser-length-sessions-vs-persistent-sessions

The default is persistent session with timeout of 2 weeks.
Maybe we can close this.
If we want to apply it to staging, perhaps it's better to move this issue to docker-geosafe.

**Comment by lucernae** [comment]
By the way, if you didn't checked `Remember me` option, it should sign out if you close the browser.
The persistent settings only takes effect if you checked this option when you log in.

**Comment by gubuntu** [comment]
not in our scope
