### ISSUE TITLE
redeploy without having to republish layers

### ISSUE THREAD

**Issue by gubuntu** [kartoza/docker-geosafe#45]
Volume mounts should be set up such that when the system is redeployed (like with daily staging updates), the layers do not need to be republished. i.e. all that is updated is the application, but thumbnails, layers, metadata etc. should just continue working.

**Comment by lucernae** [comment]
Noted, will exclude automated layer republish from staging orchestrations.
But the side effect is we have to do migrate/republish manually if the link/database changed because of update.

**Comment by gubuntu** [comment]
well if it's already in the orchestration code (part of an Ansible playbook?) then it could be made an option (default off)?

**Comment by lucernae** [comment]
Yes, it's not on this repo. It's on gitlab.
