### ISSUE TITLE
Prepare production Infrastructure.

### ISSUE THREAD

**Issue by lucernae** [kartoza/docker-geosafe#51]
We devised a generic plan to prepare infrastructure for production-grade container with rancher.
More details will be put here:

[Multi Host deployment](https://github.com/kartoza/docker-geosafe/blob/develop/docs/Multi%20Host%20Deployment.md)

Listed below is some checklist to do:

- [ ] Create ansible configuration to setup a docker image builder server. Let's aim to use Teamcity (will need at least 2 server), so it can be reused easily with other project. #52 
- [ ] Create ansible configuration to setup a rancher server and its agents (will need 1 server for rancher server UI, and several server more depending on how much agents we want). Ansible configuration for rancher server and agents should be generic, independent from project information.
- [ ] We already have shared storage system to store data. But we need to decide the backup system. It has to be plug and play and allows scaling.

**Comment by gubuntu** [comment]
@lucernae comment and close?

**Comment by gubuntu** [comment]
no comment from @lucernae so closing
