### ISSUE TITLE
Prepare docker image builder server

### ISSUE THREAD

**Issue by lucernae** [kartoza/docker-geosafe#52]
Let's aim to use Teamcity to build the docker images.

- [x] Create ansible configuration to easily setup new teamcity server.

We can use docker images to run teamcity server web UI. The web UI is lightweight.
https://www.jetbrains.com/teamcity/download/#section=docker

Requirements:
- Docker CE installed

Note:
We can use server: 78.47.48.46
I already setup a teamcity server to play and created some ansible script to play in this repo:
gitlab.com/lucernae/teamcity-setup . @manicminer, you can look at that repo and see if you can improve it for more generic uses by kartoza.

- [x] Create ansible configuration to easily setup new teamcity agents.

For this one, we prefer native access to build docker images. I've tried using teamcity agent's docker images, but it is quite slow to build docker images inside. For this particular use case, we want this agent to have native access to servers. Which in turn need these following requirements to setup using ansible script.
(Note, also taken from https://confluence.jetbrains.com/display/TCD10/Supported+Platforms+and+Environments)

Requirements:
- Oracle JDK 8 64 bit (or any jdk that works nicely with ubuntu)
- Docker CE installed (to build images)
- python, python-pip (to execute python code)
- docker-compose
- build-essentials apt packages (to execute make or other shell build tools)
- Can add more if needed later

Note:
We can use the same machine with teamcity server for now. The ansible script should make it easy to setup more teamcity agents on a different machine later on.

**Comment by gubuntu** [comment]
@lucernae please update and close

**Comment by lucernae** [comment]
Created new rancher catalogue from recent teamcity instance.
