### ISSUE TITLE
Prepare rancher server

### ISSUE THREAD

**Issue by lucernae** [kartoza/docker-geosafe#53]
We need to have our generic ansible scripts to deploy rancher server and configures rancher-agent (for the agents, we probably just needed to setup the requirements).
Relevant documentations: http://rancher.com/docs/rancher/v1.6/en/quick-start-guide/

- [ ] Prepare rancher server

Requirements:
- Docker CE Installed

Note:
We can use the same machine for teamcity for now: 78.47.48.45

- [ ] Prepare rancher setup

Requirements:

- Docker CE Installed

Note:
For the agent, I think we just have to add the agent and label it manually and then done. There's not much thing ansible can do besides preparing docker.

**Comment by gubuntu** [comment]
done, see docs in this repo and rancher.kartoza.com
