### ISSUE TITLE
django-static-data is empty

### ISSUE THREAD

**Issue by mbernasocchi** [kartoza/docker-geosafe#70]
using https://github.com/kartoza/docker-geosafe/edit/develop/deployment/production/docker/compose-files/qgis-server/docker-compose.yml in rancher results in all the JS and CSS to return a 404. analyzing the nginx container which has 'django-static-data:/usr/src/app/geonode/static_root' and it is empty.

it seems that the collect_static.py is never executed

**Comment by gubuntu** [comment]
We recommend using our new Rancher method now: https://github.com/kartoza/docker-geosafe/blob/develop/deployment/production/docs/Rancher.md

**Comment by mbernasocchi** [comment]
it is what we did :)

**Comment by lucernae** [comment]
Hi @mbernasocchi !

I'm not sure what happens with yours because we are also using the same file and it worked.
To be more specific the collect static process is happening here:
https://github.com/kartoza/docker-geosafe/blob/develop/deployment/production/docker/django_qgis-server/entry-point.sh#L10

It was executed by django services and it may take some time to build?

**Comment by mbernasocchi** [comment]
there was a permission issue when rancher set up all, it wasn't allowing django to write in that dir. I logged in the django container and couldn't even do `touch /usr/src/app/geonode/static_root/testfile`

**Comment by lucernae** [comment]
Did you setup rancher using ubuntu 16?
I'm aware that we setup read only permission, but that is on nginx service (nginx doesn't write anything).
Did you try to touch the file from inside django service?
Or maybe do you use special storage?

**Comment by timlinux** [comment]
@mbernasocchi even better check out the rancher catalogue I have set up - super easy to deploy using that.

https://github.com/kartoza/kartoza-rancher-catalogue

**Comment by mbernasocchi** [comment]
@timlinux it was with the rancher

**Comment by gubuntu** [comment]
close off this support ticket

**Comment by gubuntu** [comment]
@mbernasocchi please close if you are happy with this now
