### ISSUE TITLE
link this repo with kartoza.rancher.catalogue

### ISSUE THREAD

**Issue by timlinux** [kartoza/docker-geosafe#76]
@lucernae can you please move your rancher configs to https://github.com/kartoza/kartoza-rancher-catalogue. I have made a first one for geonode + QGIS Server and made all the options run time configurable when you deploy the stack. Please copy this approach for the GeoSAFE backend version.

I am going to add a note to rancher.md pointing to that but I think we should put all that content in the readme for https://github.com/kartoza/kartoza-rancher-catalogue and then just update the  top level readme in docker-geosafe to point to that readme. From then on we can manage all our docker-compose.yml and rancher-compose.yml files in a central place.

![screen shot 2017-10-23 at 17 04 52](https://user-images.githubusercontent.com/178003/31914192-02bae616-b84a-11e7-8265-abd92bcb2dee.png)

![licecap](https://user-images.githubusercontent.com/178003/31914179-fa2a1620-b849-11e7-8b02-06cf6f99368a.gif)

![screen shot 2017-10-23 at 17 07 15](https://user-images.githubusercontent.com/178003/31914206-13333188-b84a-11e7-8f7b-16dc8d0e60a1.png)

**Comment by gubuntu** [comment]
better still, deprecate this repo completely after migrating all to kartoza.rancher.catalogue

- [ ] and ensure all referenced images are clearly tagged so GeoNode and GeoSAFE testing, staging and production deployments can be repeated consistently.

**Comment by lucernae** [comment]
I think this needs to be a meta ticket, I mis-sized it. This ticket should cover both GeoSAFE and GeoNode + QGIS Server catalog. I updated GeoNode + QGIS Server first here for testing server: https://github.com/kartoza/kartoza-rancher-catalogue/pull/29.

**Comment by gubuntu** [comment]
done
