### ISSUE TITLE
don't reset admin credentials on update

### ISSUE THREAD

**Issue by gubuntu** [kartoza/docker-geosafe#84]
@lucernae in Gitter:
> I just remembered that our geonode docker image apparently automatically changed admin credentials to default when reinstantiated in rancher. So we probably need to fix that too.

**Comment by lucernae** [comment]
Found out another problem on this while trying to fix original issue:

- [x] Will use default GeoNode entrypoint with parameters configured according to ours
- [x] Allow customization of GeoNode's database user name GeoNode/geonode#3849

**Comment by lucernae** [comment]
>  Allow customization of GeoNode's database user name GeoNode/geonode#3849

For this, other GeoNode developer said that it was by design that they use the same name for DB name and DB user. So, we just have to follow this by convention.

The docker image now uses GeoNode entrypoint (with several modifications). It fixed this issue.
